apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('publish_comment/', views.publish_comment, name='publish_comment'),
]

apps/xfzauth/urls.py
from django.urls import path
from .import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
]

xfz_project/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('cms/', include("apps.cms.urls")),
    path('news/', include("apps.news.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/', include("apps.course.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from django import forms
from ..forms import FormMixin
from ..news.models import News, Banner


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={'required': '需要传入分类id'})
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['pub_time', 'category', 'author']


class AddBannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banner
        fields = ('priority', 'image_url', 'link_to')


class EditBannerForm(forms.ModelForm, FormMixin):
    pk = forms.IntegerField()

    class Meta:
        model = Banner
        fields = ('priority', 'image_url', 'link_to')

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_GET, require_POST
from ..news.models import NewsCategory, News, Banner
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditBannerForm
import os
from django.conf import settings
from ..news.serializers import BannerSerializer
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
# Create your views here.

app_name = 'cms'


@staff_member_required(login_url="index")
def index(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            content = form.cleaned_data.get('content')
            thumbnail = form.cleaned_data.get('thumbnail')

            category_id = form.cleaned_data.get('category')
            category_obj = NewsCategory.objects.get(pk=category_id)
            author = request.user
            News.objects.create(title=title, desc=desc, content=content, thumbnail=thumbnail, category=category_obj, author=author)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


class NewsListView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()

        page = int(request.GET.get('p', 1))
        newses = News.objects.select_related('category', 'author')

        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)

        if start or end:
            if start:
                start_date = datetime.strptime(start, "%Y/%m/%d")
            else:
                start_date = datetime(year=2018, month=9, day=1)
            if end:
                end_date = datetime.strptime(end, "%Y/%m/%d")
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category_id=category_id)

        paginator = Paginator(newses, 2)
        page_pbj = paginator.page(page)

        context_data = self.get_pagination_data(paginator, page_pbj)
        context = {
            'categories': categories,
            'newses': page_pbj.object_list,
            'page_obj': page_pbj,
            'paginator': paginator,
            'start': start,
            'end': end,
            'category_id': category_id,
            'title': title or '',
            'url_query': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or '',
            })
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page-around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page+1, num_pages+1)
        else:
            right_has_more = True
            right_pages = range(current_page+1, current_page+around_count+1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
def add_news_category(request):
    category = request.POST.get('category')
    # 判断是否存在
    exists = NewsCategory.objects.filter(name=category).exists()
    if exists:
        return restful.params_error('新闻类别已存在!')
    else:
        NewsCategory.objects.create(name=category)
        return restful.ok()


@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
        except:
            return restful.params_error("此分类id不存在！")
        return restful.ok()
    else:
        return restful.params_error(message=form.get_errors())


@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
    except:
        return restful.params_error("此分类id不存在！")
    return restful.ok()


@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    print(file)
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


def banners(request):
    return render(request, 'cms/banners.html')


def add_banner(request):
    form = AddBannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
        return restful.result(data={'banner_id': banner.pk})
    else:
        return restful.params_error(message=form.get_errors())


def banner_list(request):
    banners = Banner.objects.all()
    serializer = BannerSerializer(banners, many=True)
    return restful.result(data=serializer.data)


def delete_banner(request):
    banner_id = request.POST.get('banner_id')
    print(banner_id)
    Banner.objects.filter(pk=banner_id).delete()
    return restful.ok()


def edit_banner(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        Banner.objects.filter(pk=pk).update(image_url=image_url, link_to=link_to, priority=priority)
        return restful.ok()
    else:
        return restful.params_error(form.get_errors())

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        
        {% endblock %} | 小饭桌管理系统
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">


    <!-- jQuery 3 -->
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js'%}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>


  <![endif]-->
    {% block head %}

    {% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- 侧边栏缩放时最上方显示的文字 -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- 侧边栏展开时最上方显示的文字 -->
            <span class="logo-lg">小饭桌后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1329371998,2624202069&fm=26&gp=0.jpg" class="user-image" alt="User Image">
                            <span class="hidden-xs">李钟硕</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1329371998,2624202069&fm=26&gp=0.jpg" class="img-circle" alt="User Image">

                                <p>
                                    李钟硕 - Web Developer
                                    <small>Member since Nov. 2012</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人信息</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- 搜索框 -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_list' %}">
                        <i class="fa fa-list"></i>
                        <span>新闻列表  </span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类管理</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:banners' %}">
                        <i class="fa fa-window-restore"></i>
                        <span>轮播图管理</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}
            
            {% endblock %}
        </section>
        <section class="content">
            {% block content %}
            
            {% endblock %}
        </section>
    </div>

    <footer class="main-footer">
        <strong>小饭桌后台管理系统</strong>
    </footer>
</div>
<!-- ./wrapper -->


</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}
{% block title %}
CMS
{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#">小饭桌后台管理系统</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">请输入账号密码 </p>

        <form action="{% url 'xfzauth:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="手机号码" name="telephone">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="密码" name="password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 记住我
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}
{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}
{% block content-header %}
    <h1>新闻分类管理</h1>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary pull-right add-btn">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                                {% for category in categories %}
                                    <tr  data-pk="{{ category.id }}" data-name="{{ category.name }}">
                                        <td>{{ category.name }}</td>
                                        <td>100</td>
                                        <td>
                                            <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                            <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                        </td>
                                    </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}

{% block head %}
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
    <style>
    .left-group{
        margin-right: 20px;
    }
    </style>
{% endblock %}
{% block title %}
    新闻管理
{% endblock %}
{% block content-header %}
    新闻列表管理
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <form action="" method="get" class="form-inline">
                    <div class="form-group left-group">
                        <label for="">时间：</label>
                        {% if start %}
                            <input type="text" name="start" class="form-control" id="start-picker" readonly value="{{ start }}">
                        {% else %}
                            <input type="text" name="start" class="form-control" id="start-picker" readonly>
                        {% endif %}
                        <span>-</span>
                        {% if end %}
                            <input type="text" name="end" class="form-control" id="end-picker" readonly value="{{ end }}">
                        {% else %}
                            <input type="text" name="end" class="form-control" id="end-picker" readonly>
                        {% endif %}
                    </div>
                    <div class="form-group left-group">
                        <label for="title-input">标题：</label>
                        {% if title %}
                            <input type="text" class="form-control" name="title" id="title-input" placeholder="标题关键字">
                        {% else %}
                            <input type="text" class="form-control" name="title" id="title-input" placeholder="标题关键字" value="{{ title }}">
                        {% endif %}
                    </div>
                    <div class="form-group left-group">
                        <label for="category-input">分类：</label>
                        <select name="category" id="" class="form-control">
                            {% if category_id == 0%}
                                <option value="0" selected>所有分类</option>
                            {% else%}
                                <option value="0" selected>所有分类</option>
                            {% endif %}
                            {% for category in categories %}
                                {% if category_id == category.pk %}
                                    <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                {% else %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group left-group">
                        <button class="btn btn-primary">查询</button>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'cms:news_list' %}">清除条件</a>
                    </div>
                </form>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>标题</th>
                            <th>分类</th>
                            <th>发布时间</th>
                            <th>作者</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for news in newses %}
                            <tr>
                                <td><a target="_blank" href="{% url 'news:news_detail' news.pk %}">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time }}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="" class="btn btn-info btn-xs">编辑</a>
                                    <button class="btn btn-danger btn-xs">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <p class="pull-left">第 {{ current_page }} / 总共 {{ num_pages }} 页</p>
                <ul class="pagination pull-right">
                    {#上一页#}
                    {% if page_obj.has_previous %}
                        <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                    {% endif %}

                    {# 是否需要出现三个点 #}
                    {% if left_has_more %}
                        <li><a href="?p=1">1</a></li>
                        <li><a href="javascript:void(0);">...</a></li>
                    {% endif %}

                    {# 左边的页码 #}
                    {% for left_page in left_pages %}
                        <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                    {% endfor %}

                    {# 当前的页面 #}
                    <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                    {# 右边的页码 #}
                    {% for right_page in right_pages %}
                        <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                    {% endfor %}

                    {# 用来控制右边三个点 #}
                    {% if right_has_more %}
                        <li><a href="javascript:void(0);">...</a></li>
                        <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                    {% endif %}

                    {#下一页#}
                    {% if page_obj.has_next %}
                        <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}